raw_teams = [
    [
        "108",
        "ana",
        "ana",
        "LAA",
        "LA Angels",
        "Los Angeles Angels",
        "Angels",
        "AL",
    ],
    [
        "109",
        "ari",
        "ari",
        "ARI",
        "Arizona",
        "Arizona Diamondbacks",
        "D-backs",
        "NL",
    ],
    [
        "110",
        "bal",
        "bal",
        "BAL",
        "Baltimore",
        "Baltimore Orioles",
        "Orioles",
        "AL",
    ],
    ["111", "bos", "bos", "BOS", "Boston", "Boston Red Sox", "Red Sox", "AL"],
    ["112", "chn", "chc", "CHC", "Chi Cubs", "Chicago Cubs", "Cubs", "NL"],
    ["113", "cin", "cin", "CIN", "Cincinnati", "Cincinnati Reds", "Reds", "NL"],
    [
        "114",
        "cle",
        "cle",
        "CLE",
        "Cleveland",
        "Cleveland Indians",
        "Indians",
        "AL",
    ],
    [
        "115",
        "col",
        "col",
        "COL",
        "Colorado",
        "Colorado Rockies",
        "Rockies",
        "NL",
    ],
    ["116", "det", "det", "DET", "Detroit", "Detroit Tigers", "Tigers", "AL"],
    ["117", "hou", "hou", "HOU", "Houston", "Houston Astros", "Astros", "AL"],
    [
        "118",
        "kca",
        "kc",
        "KC",
        "Kansas City",
        "Kansas City Royals",
        "Royals",
        "AL",
    ],
    [
        "119",
        "lan",
        "la",
        "LAD",
        "LA Dodgers",
        "Los Angeles Dodgers",
        "Dodgers",
        "NL",
    ],
    [
        "120",
        "was",
        "was",
        "WSH",
        "Washington",
        "Washington Nationals",
        "Nationals",
        "NL",
    ],
    ["121", "nyn", "nym", "NYM", "NY Mets", "New York Mets", "Mets", "NL"],
    [
        "133",
        "oak",
        "oak",
        "OAK",
        "Oakland",
        "Oakland Athletics",
        "Athletics",
        "AL",
    ],
    [
        "134",
        "pit",
        "pit",
        "PIT",
        "Pittsburgh",
        "Pittsburgh Pirates",
        "Pirates",
        "NL",
    ],
    ["135", "sdn", "sd", "SD", "San Diego", "San Diego Padres", "Padres", "NL"],
    [
        "136",
        "sea",
        "sea",
        "SEA",
        "Seattle",
        "Seattle Mariners",
        "Mariners",
        "AL",
    ],
    [
        "137",
        "sfn",
        "sf",
        "SF",
        "San Francisco",
        "San Francisco Giants",
        "Giants",
        "NL",
    ],
    [
        "138",
        "sln",
        "stl",
        "STL",
        "St. Louis",
        "St. Louis Cardinals",
        "Cardinals",
        "NL",
    ],
    ["139", "tba", "tb", "TB", "Tampa Bay", "Tampa Bay Rays", "Rays", "AL"],
    ["140", "tex", "tex", "TEX", "Texas", "Texas Rangers", "Rangers", "AL"],
    [
        "141",
        "tor",
        "tor",
        "TOR",
        "Toronto",
        "Toronto Blue Jays",
        "Blue Jays",
        "AL",
    ],
    ["142", "min", "min", "MIN", "Minnesota", "Minnesota Twins", "Twins", "AL"],
    [
        "143",
        "phi",
        "phi",
        "PHI",
        "Philadelphia",
        "Philadelphia Phillies",
        "Phillies",
        "NL",
    ],
    ["144", "atl", "atl", "ATL", "Atlanta", "Atlanta Braves", "Braves", "NL"],
    [
        "145",
        "cha",
        "cws",
        "CWS",
        "Chi White Sox",
        "Chicago White Sox",
        "White Sox",
        "AL",
    ],
    ["146", "mia", "mia", "MIA", "Miami", "Miami Marlins", "Marlins", "NL"],
    [
        "147",
        "nya",
        "nyy",
        "NYY",
        "NY Yankees",
        "New York Yankees",
        "Yankees",
        "AL",
    ],
    [
        "158",
        "mil",
        "mil",
        "MIL",
        "Milwaukee",
        "Milwaukee Brewers",
        "Brewers",
        "NL",
    ],
]


teams_data = {}
for row in raw_teams:
    try:
        teams_data[int(row[0])] = {
            "team_id": int(row[0]),
            "code": row[1],
            "file_code": row[2],
            "abbrv": row[3],
            "name": row[4],
            "full_name": row[5],
            "brief_name": row[6],
            "al": row[7] == "AL",
        }
    except Exception as e:
        breakpoint()
